-- MySQL Script generated by MySQL Workbench
-- Thu Dec 19 14:09:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema religious_facility_review_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema religious_facility_review_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `religious_facility_review_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `religious_facility_review_db` ;

-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(15) NOT NULL,
  `user_pwd` VARCHAR(255) NOT NULL,
  `user_phone` CHAR(11) NOT NULL DEFAULT 'null',
  `user_email` VARCHAR(40) NOT NULL,
  `user_adr` VARCHAR(30) NOT NULL DEFAULT 'null',
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `member_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `member_email_UNIQUE` (`user_email` ASC) VISIBLE,
  UNIQUE INDEX `member_pwd_UNIQUE` (`user_pwd` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`question` (
  `author_id` BIGINT NOT NULL,
  `create_date` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `modify_date` DATETIME(6) NULL DEFAULT NULL,
  `subject` VARCHAR(200) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK9hbbb7nlsexvarrbh2l3frdj3` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FK9hbbb7nlsexvarrbh2l3frdj3`
    FOREIGN KEY (`author_id`)
    REFERENCES `religious_facility_review_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`answer` (
  `author_id` BIGINT NOT NULL,
  `create_date` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `modify_date` DATETIME(6) NULL DEFAULT NULL,
  `question_id` BIGINT NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8frr4bcabmmeyyu60qt7iiblo` (`question_id` ASC) VISIBLE,
  INDEX `FKnls7rcn98awy2wkh1mxna0f16` (`author_id` ASC) VISIBLE,
  CONSTRAINT `FK8frr4bcabmmeyyu60qt7iiblo`
    FOREIGN KEY (`question_id`)
    REFERENCES `religious_facility_review_db`.`question` (`id`),
  CONSTRAINT `FKnls7rcn98awy2wkh1mxna0f16`
    FOREIGN KEY (`author_id`)
    REFERENCES `religious_facility_review_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`answer_voter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`answer_voter` (
  `answer_id` BIGINT NOT NULL,
  `voter_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`answer_id`, `voter_user_id`),
  INDEX `FK7gny2ii3xgj1vf5ybi5lopbqo` (`voter_user_id` ASC) VISIBLE,
  CONSTRAINT `FK7gny2ii3xgj1vf5ybi5lopbqo`
    FOREIGN KEY (`voter_user_id`)
    REFERENCES `religious_facility_review_db`.`users` (`user_id`),
  CONSTRAINT `FKba6wmkj74k29bxm7877w4u6g5`
    FOREIGN KEY (`answer_id`)
    REFERENCES `religious_facility_review_db`.`answer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`religious_facility_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`religious_facility_info` (
  `facility_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `category` VARCHAR(10) NOT NULL,
  `rating` DECIMAL(3,2) NULL DEFAULT '0.00',
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`facility_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`bookmarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`bookmarks` (
  `bookmark_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `facility_id` INT NOT NULL,
  PRIMARY KEY (`bookmark_id`),
  INDEX `fk_bookmark_facility_idx` (`facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookmark_facility`
    FOREIGN KEY (`facility_id`)
    REFERENCES `religious_facility_review_db`.`religious_facility_info` (`facility_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_user_id` BIGINT NULL DEFAULT NULL,
  `create_date` DATETIME(6) NULL DEFAULT NULL,
  `question_id` BIGINT NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7e8oxffbryj1h60f1mqggxqut` (`question_id` ASC) VISIBLE,
  INDEX `FKi4xwyjsmhu648k3thg01nsqyw` (`author_user_id` ASC) VISIBLE,
  CONSTRAINT `FK7e8oxffbryj1h60f1mqggxqut`
    FOREIGN KEY (`question_id`)
    REFERENCES `religious_facility_review_db`.`question` (`id`),
  CONSTRAINT `FKi4xwyjsmhu648k3thg01nsqyw`
    FOREIGN KEY (`author_user_id`)
    REFERENCES `religious_facility_review_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`post_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`post_information` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `category` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `likes` INT NULL DEFAULT '0',
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`question_voter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`question_voter` (
  `question_id` BIGINT NOT NULL,
  `voter_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`question_id`, `voter_user_id`),
  INDEX `FKt70jmrh26ywa2pk1ttij7wp1` (`voter_user_id` ASC) VISIBLE,
  CONSTRAINT `FK15y97p03ye4pku04x3nlvush2`
    FOREIGN KEY (`question_id`)
    REFERENCES `religious_facility_review_db`.`question` (`id`),
  CONSTRAINT `FKt70jmrh26ywa2pk1ttij7wp1`
    FOREIGN KEY (`voter_user_id`)
    REFERENCES `religious_facility_review_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`reviews` (
  `review_id` BIGINT NOT NULL AUTO_INCREMENT,
  `facility_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL DEFAULT '1.00',
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`site_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`site_user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_8vlkw482t3gpnebxcm03ywk9p` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_jerlw3g2urnh55wcrm2b5kqnj` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `religious_facility_review_db`.`user_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `religious_facility_review_db`.`user_likes` (
  `like_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `review_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`like_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_review_id_idx` (`review_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
